INSERT INTO QUESTION (content) VALUES ('Em javascript, qual a diferença entre Set e Map?');
INSERT INTO QUESTION (content) VALUES ('O que é closure em javascript?');
INSERT INTO QUESTION (content) VALUES ('No CSS, qual a diferença entre pseudo-classes e pseudo-elementos?');
INSERT INTO QUESTION (content) VALUES ('Quais tags HTML são usadas para exibir os dados na forma tabular?');
INSERT INTO QUESTION (content) VALUES ('Qual a principal diferença entre CSS Grid e Flexbox?');
INSERT INTO ANSWER (content,question,status) VALUES ('Opção a',1,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',1,1);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção c',1,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção d',1,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção a',2,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',2,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',2,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção d',2,1);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção a',3,1);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',3,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção c',3,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção d',3,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção a',4,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',4,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção c',4,1);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção d',4,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção a',5,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção b',5,1);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção c',5,0);
INSERT INTO ANSWER (content,question,status) VALUES ('Opção d',5,0);